- name: template k3s daemon
  become: true
  register: k3s_service
  template:
    src: "k3s.service.j2"
    dest: "/etc/systemd/system/k3s.service"
    owner: root
    group: root
    mode: 0640

- name: enable k3s daemon
  become: true
  systemd:
    name: k3s
    daemon_reload: yes
    state: started
    enabled: yes

