kube_vip_image_tag: latest
vip_interface: eth0
vip_cidr: 32
vip_address: 192.168.42.42

kube_vip_cloud_provider_image_tag: latest
kube_vip_cloud_provider_global_cidr: 192.168.69.69/28

daemon_flags: >-
  {% if ansible_host == cluster_leader_ip %}
  --cluster-init --tls-san {{ vip_address }} --tls-san {{ cluster_dns }}
  {% else %}
  --server https://{{ cluster_leader_ip }}:6443
  {% endif %}
