# TODO:
#   1. investigate rootless
#   2. investigate MAC (apparmor/selinux)

- name: template k3s daemon
  become: true
  register: k3s_service
  template:
    src: "k3s.service.j2"
    dest: "/etc/systemd/system/k3s.service"
    owner: root
    group: root
    mode: 0640

- name: enable k3s daemon
  become: true
  systemd:
    name: k3s
    daemon_reload: yes
    state: started
    enabled: yes

- name: symlink kubectl
  become: true
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/kubectl
    state: link

- name: template kube-vip
  become: true
  template:
    src: "kube-vip.yml.j2"
    dest: "/var/lib/rancher/k3s/server/manifests/kube-vip.yml"
    owner: root
    group: root
    mode: 0640
